### ISSUE TITLE
error setting it up

### ISSUE THREAD

**Issue by cupofdeath** [Elthan/discord-spotify-bot#1]
spits out this when i run bot.py
C:\Users\tyler\Desktop\discord-spotify-bot-public>bot.py
Traceback (most recent call last):
  File "C:\Users\tyler\Desktop\discord-spotify-bot-public\bot.py", line 6, in <module>
    from cogs import music
  File "C:\Users\tyler\Desktop\discord-spotify-bot-public\cogs\music.py", line 2, in <module>
    from cogs.player import DiscordPlayer
  File "C:\Users\tyler\Desktop\discord-spotify-bot-public\cogs\player.py", line 7, in <module>
    import spotify
ImportError: No module named 'spotify'
 
i have python installed and idk where to get discord.py@async or pyspotify for windows help would be nice im on windows 10 pro

**Comment by cupofdeath** [comment]
okay so status update i went to mac os x and tried to run it since pyspotify i couldnt find for windows and the bot wont run in mac os WTH

**Comment by Elthan** [comment]
It's developed with linux in mind, don't know how to run it on Mac or Windows.
