### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by TheBrage** [Elthan/discord-spotify-bot#3]
File "bot.py", line 21
    async def on_ready():
        ^
SyntaxError: invalid syntax

**Comment by Elthan** [comment]
What python version are you running?

**Comment by TheBrage** [comment]
'/home/brage/discord-spotify-bot/bot.py' 
Traceback (most recent call last):
  File "/home/brage/discord-spotify-bot/bot.py", line 6, in <module>
    from cogs import music
  File "/home/brage/discord-spotify-bot/cogs/music.py", line 2, in <module>
    from cogs.player import DiscordPlayer
  File "/home/brage/discord-spotify-bot/cogs/player.py", line 7, in <module>
    import spotify
ImportError: No module named 'spotify'

**Comment by TheBrage** [comment]
think i just uesed python 3 to run this

**Comment by Elthan** [comment]
Do you have pyspotify installed with a key?
